### ISSUE TITLE
How do you get temp formula?

### ISSUE THREAD

**Issue by zcsd** [BjornVT/Masterproef#1]
Hi,
May I know how do you get this in seek.getTemp()?
```
temp = latestframe.at<int16_t>(pt) - 15000;
temp /= 50.338;
```
Thx,
zc

**Comment by BjornVT** [comment]
Hi,

I've calculated this with ice water and boiling water. I measured both with the seek android app and with my program. then i had pixel values for each temperature. That way i could calculate this formula.

Regards,
Bjorn

**Comment by zcsd** [comment]
Agree.
Thank you.
